CREATE TABLE db(Name TEXT PRIMARY KEY,Stock INT);
INSERT INTO db (Name, Stock)
VALUES ('Ketchup', 95);INSERT INTO db (Name, Stock)
VALUES ('Mayo', 91);INSERT INTO db (Name, Stock)
VALUES ('Ranch', 42);INSERT INTO db (Name, Stock)
VALUES ('Gig’ em Sauce', 99);INSERT INTO db (Name, Stock)
VALUES ('Buffalo Sauce', 83);INSERT INTO db (Name, Stock)
VALUES ('Honey Mustard', 31);INSERT INTO db (Name, Stock)
VALUES ('Spicy Ranch', 65);INSERT INTO db (Name, Stock)
VALUES ('Pickles', 63);INSERT INTO db (Name, Stock)
VALUES ('Patties', 96);INSERT INTO db (Name, Stock)
VALUES ('Chicken Tenders', 93);INSERT INTO db (Name, Stock)
VALUES ('Fries', 9);INSERT INTO db (Name, Stock)
VALUES ('Bun', 67);INSERT INTO db (Name, Stock)
VALUES ('Lettuce', 64);INSERT INTO db (Name, Stock)
VALUES ('Tomato', 39);INSERT INTO db (Name, Stock)
VALUES ('Onion', 58);INSERT INTO db (Name, Stock)
VALUES ('Vanilla Ice Cream', 61);INSERT INTO db (Name, Stock)
VALUES ('Chocolate Ice Cream', 34);INSERT INTO db (Name, Stock)
VALUES ('Strawberry Ice Cream', 47);INSERT INTO db (Name, Stock)
VALUES ('Brownie', 63);INSERT INTO db (Name, Stock)
VALUES ('Bacon', 81);INSERT INTO db (Name, Stock)
VALUES ('Pepper Jack Cheese', 93);INSERT INTO db (Name, Stock)
VALUES ('Texas Toast', 86);INSERT INTO db (Name, Stock)
VALUES ('Black Bean Patty', 48);INSERT INTO db (Name, Stock)
VALUES ('Kettle Chips', 93);INSERT INTO db (Name, Stock)
VALUES ('Gravy', 30);INSERT INTO db (Name, Stock)
VALUES ('Onion Rings', 58);INSERT INTO db (Name, Stock)
VALUES ('Tater Tots', 6);INSERT INTO db (Name, Stock)
VALUES ('Cold Brew', 85);INSERT INTO db (Name, Stock)
VALUES ('Coffee Grounds', 25);